include themes/noctalia.conf

font_size 16.0
font_family JetBrainsMono Nerd Font Mono

background_opacity 0.95
window_padding_width 10

cursor_shape block
cursor_shape_unfocused hollow
cursor                   #bdae93
cursor_text_color        #665c54

url_color                #458588

